// This file is auto-generated by tools/quantize_brain.py
// It contains the TFLite Int8 quantized weights required for ESP32 inference.

#include <stdint.h>

// ESP32 strictly requires 16-byte alignment or it will memory panic while reading weights.
#ifdef __has_attribute
#define HAVE_ATTRIBUTE(x) __has_attribute(x)
#else
#define HAVE_ATTRIBUTE(x) 0
#endif
#if HAVE_ATTRIBUTE(aligned) || (defined(__GNUC__) && !defined(__clang__))
#define DATA_ALIGN_ATTRIBUTE __attribute__((aligned(16)))
#else
#define DATA_ALIGN_ATTRIBUTE
#endif

extern const unsigned char g_bee_brain_model_data[] DATA_ALIGN_ATTRIBUTE = {
    // Dummy model bytes. Note: these will be automatically injected by the quantizer.
    0x00, 0x00, 0x00, 0x00
};

extern const int g_bee_brain_model_data_len = 4;

